//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodaysAlphaReactor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodaysAlphaReactor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileQuit {
            get {
                return ResourceManager.GetString("MenuFileQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSetting {
            get {
                return ResourceManager.GetString("MenuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month Day Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettingMdFormat {
            get {
                return ResourceManager.GetString("MenuSettingMdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always on Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewAot {
            get {
                return ResourceManager.GetString("MenuViewAot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hide Menu (Press Alt key to redisplay) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewHideMenu {
            get {
                return ResourceManager.GetString("MenuViewHideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day-Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthDayFormatDayHyphenMonth {
            get {
                return ResourceManager.GetString("MonthDayFormatDayHyphenMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day/Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthDayFormatDaySlashMonth {
            get {
                return ResourceManager.GetString("MonthDayFormatDaySlashMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month-Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthDayFormatMonthHyphenDay {
            get {
                return ResourceManager.GetString("MonthDayFormatMonthHyphenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month/Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthDayFormatMonthSlashDay {
            get {
                return ResourceManager.GetString("MonthDayFormatMonthSlashDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Alpha Reactor&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryString {
            get {
                return ResourceManager.GetString("QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today&apos;s Alpha Reactor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
